### ISSUE TITLE
SD Initialization Fails Occasionally

### ISSUE THREAD

**Issue by stergiosba** [Javierma/SD-card-TivaC-library#1]
Hello the SD card initialization fails sometimes.

My setup:
**MCU**: [TM4C123GH6PM](https://www.ti.com/product/TM4C123GH6PM)
**SD-Board**: [Waveshare SD](https://www.waveshare.com/wiki/Micro_SD_Storage_Board)
**SD-Card**: [Sandisk Ultra microSDHC 32GB U1 A1](https://www.amazon.com/SanDisk-Ultra-microSDHC-Memory-Adapter/dp/B08GY9NYRM)

Initially I though my card was faulty but I managed to fix the issue with ideas from this [post](https://arduino.stackexchange.com/questions/21368/sd-card-initialization-fails-randomly). Simply by adding this:
`while (send_command(CMD0, 0,SSI_number)!= 1) {SysCtlDelay(200);}` before:
`if(send_command(CMD0, 0,SSI_number) == 1)` in sdcard.c @ line 309

If TivaWare is used (as in my case), SysCtlDelay() is added by `#include "driverlib/sysctl.h"`, of course a custom delay function would also work.

P.S. I am not proposing this as a fix because it worked only for my SD Card (and I don't have another to test) but before that I had 7/10 fails and now 20/20 successes. Also when it was failing  CMD0 command always returned 9, I don't know if this can help in anyway. Maybe you can find a more elegant solution.

Cheers

**Comment by Javierma** [comment]
Hi @Khanax:

Many thanks for your comment and your interest in the project. I remember having the same issue that you some time ago until I made use of another SD card adapter with the CD (Card Detector) pin, which solved the issue for me, but I guess it may depend on having the CD pin, the adapter used, etc.
Based on your suggestion and using an existing function in the code for delays, I just modified it so the initialisation now looks like the following, giving time to the SD card to be started while avoiding an infinite loop if for example you forget inserting the card or it really is faulty:

```
        i=0;
	/* Give the card some time to complete initialisation */
	while(i<10 && send_command(CMD0, 0, SSI_number) != 1)
	{
	    SysTick_Wait50ms(4);
	    i++;
	}
	i=0;
	/*Checks if SD card is in IDLE mode. If so, response will be 1*/
	if(send_command(CMD0, 0, SSI_number) == 1)
```

Regards,
Javier
